### ISSUE TITLE
WebOS Update Message

### ISSUE THREAD

**Issue by Pir8pete** [webosbrew/webos-homebrew-channel#204] opened 2024-12-14 20:29 UTC
On a cold boot, with updates disabled, if LG has an update available it will displays a message to do the update every time.  Please have this auto ignored.   Or is it safe to update an not loose the root?

And if your going to ask Safemode is turned off in options

![IMG_1663](https://github.com/user-attachments/assets/4e0748ba-8318-4fc7-bc54-9d2364434e77)

I do not want to install adGuard on my main router as my other TV's need to be updated when available, plus i don't want to run extra processes in the background of my router.

snu.lge.com
su.lge.com
su-ssl.lge.com
snu-dev.lge.com
su-dev.lge.com
nsu.lge.com

**Comment by shooflyshoo** [comment] 2024-12-14 21:43
Plus one to this request. I tried to update my router to block these servers, but it didn't work for me :(

**Comment by throwaway96** [comment] 2024-12-15 18:16
Duplicate of #96.

**Closed by throwaway96** 2024-12-15 18:16 UTC
